name: Tests

on:
  # schedule:
  #   - cron: "26 5 * * *" # Every day, 05:26 UTC
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "syncedlyrics/**"
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "syncedlyrics/**"
  workflow_dispatch:

jobs:
  provider-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Installing poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Inatalling dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: Running provider tests
        run: poetry run python -m pytest --durations=0 -vv -s --log-cli-level=DEBUG tests.py
